# Generated by Django 2.2.6 on 2019-10-16 01:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Job name', max_length=30)),
                ('description', models.TextField(help_text='Job description', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Job Titles',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Subject code', max_length=12)),
                ('name', models.CharField(blank=True, help_text='Subject name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code assigned to the faculty', max_length=12)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], help_text='Gender', max_length=1)),
                ('first_name', models.CharField(help_text='First name', max_length=20)),
                ('last_name', models.CharField(help_text='Last name', max_length=20)),
                ('birth_date', models.DateField(default=datetime.date.today, help_text='Birth date')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number', max_length=12)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.JobTitle')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
